# Assignment 3

# Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3. 

In [10]:
import numpy as np
l=np.arange(2,51,3)
print(l)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2:
Accept two lists of 5 elements each from the user.  Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it. 

In [45]:
l1=[]
l2=[]
i=1
j=1
while i<=5:
    n1=int(input("Enter the number of first list="))
    l1.append(n1)
    i=i+1
while j<=5:
    n2=int(input("Enter the number of second list="))
    l2.append(n2)
    j=j+1
print("List 1=",l1)
print("List 2=",l2)
arr1=np.array(l1)   #convert to a list in a array
arr2=np.array(l2)   #convert to a list in a array
print(type(arr1))
print(type(arr2))
print("Array 1=",arr1)
print("Array 2=",arr2)
a=np.concatenate((arr1,arr2))
print("Concatenation of the array=",a)
a.sort()
print("Sort the array=",a)

Enter the number of first list=4
Enter the number of first list=6
Enter the number of first list=2
Enter the number of first list=4
Enter the number of first list=9
Enter the number of second list=5
Enter the number of second list=10
Enter the number of second list=0
Enter the number of second list=2
Enter the number of second list=7
List 1= [4, 6, 2, 4, 9]
List 2= [5, 10, 0, 2, 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Array 1= [4 6 2 4 9]
Array 2= [ 5 10  0  2  7]
Concatenation of the array= [ 4  6  2  4  9  5 10  0  2  7]
Sort the array= [ 0  2  2  4  4  5  6  7  9 10]


# Question 3:
Write a code snippet to find the dimensions of a ndarray and its size. 

In [58]:
# 1D array
arr1=np.arange(1,11)
print(arr1)
print(arr1.size)
print(arr1.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
10
1


In [59]:
#2D Array
arr1=np.arange(1,11).reshape(2,5)
print(arr1)
print(arr1.size)
print(arr1.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
2


# Question 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

In [76]:
# np.newaxis

A=np.arange(4)
print(A)
print(A.shape)

r=A[np.newaxis,:]        #insert the axis along first dimension
print(r.shape)

c=A[:,np.newaxis]        #insert the axis along second dimension
print(r.shape)

[0 1 2 3]
(4,)
(1, 4)
(1, 4)


In [86]:
# np.expand_dims

A=np.arange(4)
print(A)
print(A.shape)

B=np.expand_dims(A, axis=0)
print(B)
print(B.shape)

B=np.expand_dims(A, axis=1)
print(B)
print(B.shape)

[0 1 2 3]
(4,)
[[0 1 2 3]]
(1, 4)
[[0]
 [1]
 [2]
 [3]]
(4, 1)


# Question 5:
Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack() 

In [105]:
arr1=np.arange(5)
arr2=np.arange(5,10)
print(arr1)
print(arr2)
print()

a1=np.square(arr1)         #square of the arr1
a2=np.square(arr2)         #square of the arr2
print(a1)
print(a2)
print()

v1=np.vstack((a1,a2))     # stack them vertically
print(v1)
print()

v2=np.hstack((a1,a2))     # stack them horizontally
print(v2)



[0 1 2 3 4]
[5 6 7 8 9]

[ 0  1  4  9 16]
[25 36 49 64 81]

[[ 0  1  4  9 16]
 [25 36 49 64 81]]

[ 0  1  4  9 16 25 36 49 64 81]


# Question 6:
How to get unique items and counts of unique items? 

In [108]:
arr=np.array([1,1,2,2,2,3,4,5])
print(arr)
s=set(arr)  # set is used to get the unique items
print(s)
n=len(s)    # len is used to the count the unique items
print(n)

[1 1 2 2 2 3 4 5]
{1, 2, 3, 4, 5}
5
